# Generated by Django 2.1.9 on 2019-07-14 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActInteg',
            fields=[
                ('v_type', models.CharField(db_column='V_type', max_length=50, primary_key=True, serialize=False)),
                ('t_integration', models.IntegerField(blank=True, db_column='T_integration', null=True)),
            ],
            options={
                'db_table': 'Act_integ',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ActJoin',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_column='User_ID', max_length=20)),
                ('v_numb', models.IntegerField(db_column='V_numb')),
                ('j_btime', models.DateField(blank=True, db_column='J_btime', null=True)),
                ('j_etime', models.DateField(blank=True, db_column='J_etime', null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'Act_join',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ActVolum',
            fields=[
                ('act_numb', models.AutoField(db_column='Act_numb', primary_key=True, serialize=False)),
                ('v_name', models.CharField(db_column='V_name', max_length=50)),
                ('v_btime', models.DateField(blank=True, db_column='V_btime', null=True)),
                ('v_etime', models.DateField(blank=True, db_column='V_etime', null=True)),
                ('v_describe', models.TextField(blank=True, db_column='V_describe', null=True)),
                ('v_type', models.ForeignKey(blank=True, db_column='V_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lovept.ActInteg')),
            ],
            options={
                'db_table': 'Act_Volum',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ComJoin',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=50)),
                ('rea_name', models.CharField(db_column='Rea_name', max_length=50)),
                ('res_telenumb', models.CharField(db_column='Res_telenumb', max_length=20)),
                ('c_btime', models.DateField(blank=True, db_column='C_btime', null=True)),
                ('c_etime', models.DateField(blank=True, db_column='C_etime', null=True)),
                ('v_numb', models.IntegerField(blank=True, null=True)),
                ('counts', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Com_join',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('user_id', models.CharField(db_column='User_ID', max_length=20, primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_column='User_name', max_length=50)),
                ('user_passwd', models.CharField(db_column='User_passwd', max_length=50)),
                ('user_telenumb', models.CharField(db_column='User_telenumb', max_length=50)),
                ('user_tname', models.CharField(db_column='User_tname', max_length=50)),
                ('user_integration', models.IntegerField(blank=True, db_column='User_integration', null=True)),
            ],
            options={
                'db_table': 'UserInfo',
                'managed': True,
            },
        ),
    ]
