# Generated by Django 2.2.3 on 2019-07-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=25)),
                ('user_name', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('user_passwd', models.CharField(max_length=16)),
            ],
        ),
    ]
